import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
    container: {
    flex: 1,
    backgroundColor: '#EBF5F9',
  },
//   headerBackground: {
//   position: 'absolute',
//   top: 0,
//   left: 0,
//   right: 0,
//   height: 280,
//   backgroundColor: '#1f66c1',
//   borderBottomLeftRadius: 15,
//   borderBottomRightRadius: 15,
//   zIndex: -1,
// },
  headerContainer: {
    backgroundColor: '#1f66c1',
    alignItems: 'center',
    paddingTop: 140,
    paddingBottom: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    overflow: 'hidden',
  },
curve: {
  position: 'absolute',
  left: 0,
  bottom: 0,
},
  circle: {
    backgroundColor: '#1f66c1',
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 4,
    borderColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  accuracy: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
  },
  subtext: {
    fontSize: 13,
    textAlign: 'center',
    color: '#fff',
  },
  latLngContainer: {
    marginTop: 70,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingHorizontal: 20,
  },
  box: {
    alignItems: 'center',
    flex: 1,
  },
  label: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1f66c1',
  },
  value: {
    fontSize: 20,
    fontWeight: '600',
    marginTop: 5,
  },
  subvalue: {
    fontSize: 14,
    marginTop: 3,
    color: '#666',
  },
  divider: {
    width: .5,
    height: 60,
    marginTop: 20,
    backgroundColor: '#000',
    marginHorizontal: 10,
  },
  alertBox: {
  marginTop: 20,
  marginHorizontal: 20,
  padding: 15,
  borderRadius: 10,
  backgroundColor: '#fff3cd',
  borderColor: '#ffeeba',
  borderWidth: 1,
  elevation: 2,
},
alertTitle: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#856404',
},
aqhiValue: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#856404',
  marginTop: 5,
},
aqhiLevel: {
  fontSize: 14,
  marginTop: 5,
  color: '#856404',
},
});