export const AppStrings = {
  token: 'TOKEN',
  user: 'USER',
  pleaseEnterYourDetails: 'Please enter your details.',
  welcomeBackAmeya: 'Welcome Back To Ameya!',
  emailAddress: 'Email Address',
  password: 'Password',
  rememberMe: 'Remember me',
  forgotPassword: 'Forgot password',
  signIn: 'Sign In',
  invalidEmailPasswordError:
    'Invalid email and / or password. Please try again.',
  forgotPasswordHeading: 'Forgot Password',
  forgotPasswordBody:
    'Enter your email below to request a verification code for your password.',
  continue: 'Continue',
  setNewPassword: 'Set New Password',
  resetPasswordHeading: 'Reset Password',
  havingTrouble: 'Having trouble? Contact support by email:',
  supportEmailID: 'support@ameya.ca',
  createNewPassword: 'Create New Password',
  confirmNewPassword: 'Confirm New Password',
  login: 'Log in',
  alreadyHaveAnAccount: 'Already have an account? ',
  authenticateAccount: 'Authenticate Account',
  enterSixDigitCode: 'Enter the 6-digit code sent to',
  verify: 'Verify',
  sendNewCode: 'Send New Code',
  welcomeToAmeya: 'Welcome to Ameya',
  enterYourEmailAddressToBeginTheProcess:
    'Enter your email address to \n begin the process',
  termsTap: 'By tapping continue, you agree to our',
  termsOfService: 'Terms of service',
  privacyPolicy: 'Privacy policy',
  verifyYourAccount: 'Verify Your Account',
  didNotGetCode: 'Didn’t get a code? ',
  resendCode: 'Resend Code',
  stepIntoWellness: 'Step Into Wellness',
  accountCreated: 'Account Created',
  yourInformationIsEncrypted:
    'Your information is encrypted. We are dedicated to creating an environment that is safe, secure, and easy for our users. ',
  verifyingYourCredentials: 'Verifying your credentials...',
  validatingOtp: 'Validating your Verification code...',
  pleaseWaitGeneratingOtp:
    "Please wait, we're generating a new Verification code...",
  profileSettings: 'Profile Settings',
  logout: 'Log Out',
  participant: 'PARTICIPANT',
  accountVerified: 'Account Verified Successfully',
  hello: 'Hello,',
  greatGoing: 'Great Going!',
  youAreRightTrack: 'You are right on track',
  nutrition: 'Nutrition',
  activity: 'Activity',
  movement: 'Movement',
  survey: 'Survey',
  comingSoon: 'Coming\nSoon',
  moreToGo: 'more\nto go',
  complete: 'complete',
  trackPhysicalActivitySeamlessly: 'Track Physical Activity Seamlessly',
  trackMovementSeamlessly: 'Track Movement Seamlessly',
  trackSurveySeamlessly: 'Track Survey Seamlessly',
  daysToGo: 'days\nto go',
  dayToGo: 'day\nto go',
  foodLogsToGo: 'food logs\nto go',
  foodLogToGo: 'food log\nto go',
  movementsToGo: 'movements\nto go',
  movementToGo: 'movement\nto go',
  taskCompleted: 'Task\nCompleted',
  dueToday: 'Due today',
  foodJournal: 'Food Journal',
  logFood: 'Log Food',
  waterJournal: 'Water Journal',
  done: 'Done',
  newRecipe: 'New Recipe',
  newFood: 'New Food',
  scanBarcode: 'Scan Barcode',
  scanFood: 'Scan Food',
  personalInfo: 'Personal Info',
  basicDetails: 'Basic Details',
  fullName: 'Full Name',
  dateOfBirth: 'Date of Birth',
  address: 'Address',
  contact: 'Contact',
  toUpdateInformation:
    'Contact your research or clinical team to update information.',
  careProvierInfo: 'Care Provider Information',
  organization: 'Organization',
  clinic: 'Clinic/Cohort',
  hcPractitioner: 'Healthcare Practitioner',
  accountInformation: 'Account Information',
  emailId: 'Email ID',
  archive: 'Archive',
  favorites: 'Favorites',
  myRecipes: 'My Recipes',
  myFoods: 'My Foods',
  general: 'General',
  health: 'Health',
  account: 'Account',
  devices: 'Devices',
  privacyNotice: 'Privacy Notice',
  termsOfUse: 'Terms of Use',
  terms: 'Terms',
  recipeCard: 'RecipeCard',
  ingredient: 'Ingredient',
  toppings: 'Add-ons',
  addIngredient: 'Add Ingredient',
  addToppings: 'Add-ons',
  save: 'Save',
  trackNutrtionSeamlessly: 'Track Nutrition Seamlessly',
  noLogs: 'No Logs Found',
  noDevices: 'No Connected Devices Found',
  nutritionPerServing: 'Nutrition Per Serving',
  nutritionPortionSize: 'Nutrition Portion Size',
  message: 'Message',
  myReports: 'My Reports',
  comingSoonHeading: 'Coming Soon!',
  comingSoonDescription: 'Stay tuned, this feature will be available soon',
  updateRecipeAndLogFood: 'Update Recipe and Log Food',
  saveRecipeAndLogFood: 'Save Recipe and Log Food',
  updateFoodAndLogFood: 'Update Food and Log Food',
  saveFoodAndLogFood: 'Save Food and Log Food',
  logFoodTo: 'Log Food To',
  doneLoggingForTheDay: 'Done logging for the day?',
  completeDay: 'Complete Day',
  editDay: 'Edit Day',
  greatJob: 'Great Job! Day complete!',
  email: 'Email',
  healthData: 'Health Data',
  connected: 'Device Connected',
  connectDevice: 'Connect Device',
};

export const environmentTypes = {
  development: 'development',
  qa: 'qa',
  production: 'production',
};

export const SERVINGS = {
  singular: [
    {unitName: 'Bottle', label: 'Bottle', quantity: 1},
    {unitName: 'Box', label: 'Box', quantity: 1},
    {unitName: 'Can', label: 'Can', quantity: 1},
    {unitName: 'Container', label: 'Container', quantity: 1},
    {unitName: 'Cube', label: 'Cube', quantity: 1},
    {unitName: 'Cup', label: 'Cup', quantity: 1},
    {unitName: 'Dessertsspoon', label: 'Dessertsspoon', quantity: 1},
    {unitName: 'Each', label: 'Each', quantity: 1},
    {unitName: 'Gallon', label: 'Gallon', quantity: 1},
    {unitName: 'Grams', label: 'Grams', quantity: 1},
    {unitName: 'Jar', label: 'Jar', quantity: 1},
    {unitName: 'Kilogram', label: 'Kilogram', quantity: 1},
    {unitName: 'Metric Cup', label: 'Metric Cup', quantity: 1},
    {unitName: 'Microgram', label: 'Microgram', quantity: 1},
    {unitName: 'Milligram', label: 'Milligram', quantity: 1},
    {unitName: 'Millilitre', label: 'Millilitre', quantity: 1},
    {unitName: 'Ounce', label: 'Ounce', quantity: 1},
    {unitName: 'Package', label: 'Package', quantity: 1},
    {unitName: 'Piece', label: 'Piece', quantity: 1},
    {unitName: 'Pint', label: 'Pint', quantity: 1},
    {unitName: 'Pot', label: 'Pot', quantity: 1},
    {unitName: 'Pouch', label: 'Pouch', quantity: 1},
    {unitName: 'Pound', label: 'Pound', quantity: 1},
    {unitName: 'Punnet', label: 'Punnet', quantity: 1},
    {unitName: 'Quart', label: 'Quart', quantity: 1},
    {unitName: 'Scoop', label: 'Scoop', quantity: 1},
    {unitName: 'Serving', label: 'Serving', quantity: 1},
    {unitName: 'Slice', label: 'Slice', quantity: 1},
    {unitName: 'Stich', label: 'Stich', quantity: 1},
    {unitName: 'TableSpoon', label: 'TableSpoon', quantity: 1},
    {unitName: 'Tablet', label: 'Tablet', quantity: 1},
    {unitName: 'TeaSpoon', label: 'TeaSpoon', quantity: 1},
  ],
  plural: [
    {unitName: 'Bottles', label: 'Bottles', quantity: 1},
    {unitName: 'Boxes', label: 'Boxes', quantity: 1},
    {unitName: 'Cans', label: 'Cans', quantity: 1},
    {unitName: 'Containers', label: 'Containers', quantity: 1},
    {unitName: 'Cubes', label: 'Cubes', quantity: 1},
    {unitName: 'Cups', label: 'Cups', quantity: 1},
    {unitName: 'Dessertsspoons', label: 'Dessertsspoons', quantity: 1},
    {unitName: 'Eaches', label: 'Eaches', quantity: 1},
    {unitName: 'Gallons', label: 'Gallons', quantity: 1},
    {unitName: 'Grams', label: 'Grams', quantity: 1},
    {unitName: 'Jars', label: 'Jars', quantity: 1},
    {unitName: 'Kilograms', label: 'Kilograms', quantity: 1},
    {unitName: 'Metric Cups', label: 'Metric Cups', quantity: 1},
    {unitName: 'Micrograms', label: 'Micrograms', quantity: 1},
    {unitName: 'Milligrams', label: 'Milligrams', quantity: 1},
    {unitName: 'Millilitres', label: 'Millilitres', quantity: 1},
    {unitName: 'Ounces', label: 'Ounces', quantity: 1},
    {unitName: 'Packages', label: 'Packages', quantity: 1},
    {unitName: 'Pieces', label: 'Pieces', quantity: 1},
    {unitName: 'Pints', label: 'Pints', quantity: 1},
    {unitName: 'Pots', label: 'Pots', quantity: 1},
    {unitName: 'Pouches', label: 'Pouches', quantity: 1},
    {unitName: 'Pounds', label: 'Pounds', quantity: 1},
    {unitName: 'Punnets', label: 'Punnets', quantity: 1},
    {unitName: 'Quarts', label: 'Quarts', quantity: 1},
    {unitName: 'Scoops', label: 'Scoops', quantity: 1},
    {unitName: 'Servings', label: 'Servings', quantity: 1},
    {unitName: 'Slices', label: 'Slices', quantity: 1},
    {unitName: 'Stichs', label: 'Stichs', quantity: 1},
    {unitName: 'TableSpoons', label: 'TableSpoons', quantity: 1},
    {unitName: 'Tablets', label: 'Tablets', quantity: 1},
    {unitName: 'TeaSpoons', label: 'TeaSpoons', quantity: 1},
  ],
};
